name: PR CI
on:
  pull_request:
    types: [opened, reopened, synchronize, ready_for_review]
jobs:
    test:
      strategy:
        matrix:
          os: [ ubuntu-latest, macos-latest, windows-latest ]
      runs-on: ${{ matrix.os }}
      steps:
        - name: Checkout repo
          uses: actions/checkout@v2
        - name: Setup Go
          uses: actions/setup-go@v2
          with:
            go-version-file: './go.mod'
        - run: |
            make test
    lint:
      name: 'Check linting'
      runs-on: ubuntu-latest
      steps:
        - name: Checkout repo
          uses: actions/checkout@v2
        - name: Setup Go
          uses: actions/setup-go@v2
          with:
            go-version-file: './go.mod'
        - run: |
            make lint
            make test